# Generated by Django 3.2.9 on 2021-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(auto_created='titulo', blank=True, max_length=15, null=True),
        ),
    ]
