# Generated by Django 3.2.9 on 2021-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211111_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado_atual',
            field=models.CharField(choices=[('postado', 'postado'), ('rascunha', 'rascunha')], max_length=15),
        ),
    ]
